import React from "react";
import Navbar from "../../components/navbar/Navbar";

const DashboardPage = ({onExit}) => {
  return (
    <div style={{width: '100%', position:'relative'}}>
      <Navbar onExit={onExit}/>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo veniam sequi illo, repellendus necessitatibus laudantium odit, omnis nihil tenetur voluptatem, corporis accusantium! Id atque est distinctio mollitia architecto neque natus.
      Debitis velit repellendus incidunt assumenda recusandae nesciunt numquam voluptatem et, quisquam nulla ab. Maiores quidem amet accusantium perspiciatis corrupti, odio id ratione, laboriosam voluptas voluptatum facilis necessitatibus doloribus labore cumque.
      Quis alias quos velit temporibus voluptas ducimus veniam nobis aut maxime, dolores asperiores nesciunt doloremque enim molestias voluptates nam dolorem magnam explicabo aliquid aperiam laudantium non pariatur. Tempora, cupiditate debitis!
      Eaque odit libero incidunt culpa itaque atque repellendus veniam perferendis maiores laborum mollitia vitae hic provident quas commodi, exercitationem ex sapiente asperiores similique sunt, voluptate magni earum quibusdam quod. Fugit.
      Quis laudantium ad, molestiae ratione dignissimos in sapiente veniam, ab modi facilis ullam, autem quos non consequatur reiciendis vel. Atque reiciendis magni minus tenetur, pariatur a ullam quisquam explicabo obcaecati.
      Voluptatum perspiciatis maxime facere ratione est quam illum magnam minima maiores quaerat minus officia id dolorem nobis dolores laborum odit, beatae itaque. Error saepe officia debitis quidem doloremque commodi delectus.
      Tenetur, ex quaerat sint sequi ducimus facere numquam. Nemo alias ex dignissimos corrupti nobis quas facere in beatae reiciendis asperiores ipsum laborum totam quaerat nulla velit aut, cumque officia et.
      Culpa asperiores cupiditate sapiente consequuntur provident? Itaque praesentium similique nesciunt corporis sapiente tempore eligendi quis! Odio repudiandae animi quam error temporibus mollitia quia debitis esse, a laboriosam optio voluptates laudantium.
      Praesentium laborum pariatur magnam sequi asperiores totam, numquam voluptatum incidunt repellendus, delectus natus iure! Incidunt nemo quisquam laudantium? Hic repellat accusantium inventore quam recusandae non nihil sunt ipsam sed magnam.
      Velit, officiis animi eveniet ipsam dolor, beatae nostrum repellendus officia incidunt doloribus, est laborum tenetur porro. Fugit quas dicta nihil, natus ea vitae obcaecati, animi, amet itaque illum rem nulla.
      Nisi quae sapiente, rem facere natus fugiat dolorum velit officiis maxime incidunt tempora. Dicta accusamus nulla praesentium aspernatur pariatur optio necessitatibus aliquam, vero molestiae repudiandae unde ratione? Placeat, quod id.
      Necessitatibus velit labore vero quae, voluptatibus magnam accusantium possimus vel minus doloremque fugit officia, nostrum commodi! Debitis dicta laudantium minima quisquam et quasi accusamus doloremque. Assumenda molestiae obcaecati excepturi consequatur!
      Qui neque architecto possimus eum. Obcaecati sint perspiciatis quod quae, doloribus magni, excepturi reprehenderit, enim aspernatur assumenda nam labore fuga soluta eaque minus ad! Labore, unde? Quidem enim vero sapiente?
      Recusandae, quasi dignissimos cum tenetur repellat dicta nobis maiores modi! Quo libero non, vel adipisci doloremque quas atque saepe ipsam ratione rem, hic iste, inventore earum unde magnam fugiat rerum!
      Maiores inventore suscipit reprehenderit quia unde culpa eos debitis facere molestias provident cum exercitationem impedit recusandae amet corporis voluptatibus, esse ea quae animi hic magni! Ipsum consectetur eaque sed nostrum.
      Facere laborum eum a. Expedita rerum, ducimus, beatae maiores a temporibus delectus ab ad sit nemo unde ut nam doloremque, quaerat natus voluptate? Officiis consectetur reiciendis recusandae soluta ducimus aut.
      Tempore, nostrum accusantium maxime voluptatem harum voluptatibus! Quia quod esse quas debitis, odio molestias quasi quis repellendus tempore doloremque ipsa neque molestiae officiis eos est alias dolores voluptate minus excepturi.
      Deleniti facilis dolorem reprehenderit ipsa consectetur distinctio numquam ea non, nostrum veritatis repudiandae repellendus magni perspiciatis nesciunt, placeat rerum porro labore! Optio laboriosam hic beatae aliquid, officiis molestiae. Harum, saepe!
      Temporibus, totam saepe. Accusantium quasi repellat voluptates reiciendis itaque aliquid maxime incidunt sapiente. Ea beatae cum doloribus error iure consequatur ut, hic quas cumque aut, recusandae vero, fugit amet atque!
      Inventore dolorem dolore quos. Nobis dolor sed consequuntur veniam molestias animi commodi magnam, ea quos similique repellendus aspernatur quam ullam explicabo, perferendis consectetur consequatur, ipsa officiis fugiat ipsam facilis! Eos.
      Voluptate vel eius quo sequi unde reprehenderit eligendi, ut nobis architecto aliquid et eveniet aspernatur dolores perspiciatis sed sit ea id maiores quidem, ullam facilis iusto labore! Cumque, fugit consequatur.
      Quas obcaecati laboriosam, ipsa modi dolore eum? Tempora id aspernatur quam voluptates sit, praesentium fuga. Iste laudantium, amet quae, nisi reprehenderit commodi placeat error repellat deleniti nihil blanditiis quas repudiandae?
      Quasi, aliquam fuga maiores et eveniet omnis, ab error possimus placeat tempora nihil ea quae quia fugiat temporibus cumque ipsam ipsum optio? Fugiat, eaque commodi fugit iure adipisci repellendus inventore.
      Autem ipsa id sed beatae, excepturi consequuntur porro omnis, consequatur similique enim numquam maxime maiores? Quasi voluptatum quibusdam ducimus quidem perspiciatis repellat nesciunt possimus nulla praesentium? Quibusdam nesciunt molestiae consequatur?
      Asperiores magni alias earum explicabo quos, in reiciendis deserunt facere sint accusamus, dolorum dolore rerum consequatur eius quidem quae nesciunt autem atque molestiae eaque ea ad cumque minima. Fuga, sunt.
      Aspernatur magni laudantium nam cumque ipsum, culpa fugiat impedit in possimus libero eum modi exercitationem laborum placeat nemo aut id provident velit facere veniam doloribus numquam quaerat repellat vero! Architecto.
      Praesentium, exercitationem quae? Vitae dicta earum iure, porro minus vero hic voluptate nam tenetur placeat soluta praesentium amet labore, incidunt id magnam officia. Minus inventore alias minima, culpa fuga voluptatum.
      A nisi, repellendus dolores rem hic tempora voluptas similique, animi aspernatur maxime natus? Maiores illo amet adipisci incidunt. Culpa debitis dolor cupiditate a minima cum nemo dignissimos doloribus aut voluptas.
      Praesentium suscipit expedita iure voluptas nisi itaque excepturi et quisquam dolorem, quae incidunt dicta! Placeat, a debitis? Quasi, atque quis. Pariatur vitae error impedit ratione deleniti temporibus quo quae voluptatibus.
      Laboriosam voluptate fuga vitae omnis assumenda nisi voluptatem consequuntur accusantium quisquam. Commodi, facilis maiores natus nisi quod alias cupiditate itaque impedit excepturi quisquam totam nesciunt quis optio perferendis dolores recusandae.
      Facere corrupti minima veniam quas eaque laboriosam itaque nihil aperiam eos sint quam ad eveniet doloremque, exercitationem, dolorum aut quos odio quod architecto adipisci explicabo at. Consequatur, nemo dicta. Quia.
      Molestias magnam fuga distinctio magni ratione, deserunt atque possimus modi nulla a inventore ipsa, cumque facere aspernatur praesentium dicta in harum? Qui, sed labore odit quo ut incidunt soluta modi.
      Nesciunt corporis ducimus vel cum, commodi at magni quidem aut! Ex, a repudiandae distinctio explicabo voluptatibus quisquam quod eum, reiciendis earum omnis quo aperiam. Aperiam nihil ut ab debitis cupiditate.
      Perspiciatis repellat consectetur dignissimos blanditiis doloribus dolor beatae suscipit neque fuga qui? Voluptates molestiae minus iusto commodi, voluptate unde maiores provident tempora blanditiis corrupti dolorem mollitia iste amet numquam dolor.
      Ex unde, eligendi sequi nostrum soluta eaque commodi tempora et repellendus nulla eos non voluptates tempore delectus facere ducimus reiciendis eveniet! Ut maiores repellat, alias iste sit dolorum quos illum.
      Laudantium expedita nemo eum quo aspernatur eos eius quaerat velit, omnis excepturi voluptatibus, architecto harum numquam fugiat deserunt a nesciunt accusamus incidunt voluptas beatae necessitatibus maiores alias eligendi! Eveniet, repellat?
      Ea, incidunt eaque. Modi assumenda animi saepe esse earum, amet aperiam voluptatum quae perferendis ullam asperiores quod non quasi, harum omnis magni deserunt nemo ut mollitia ipsum, possimus nesciunt sit?
      Voluptatum, cumque! Similique animi tempore magnam eos atque ex veniam dicta consequuntur reprehenderit quod. Saepe officiis ipsa odio natus sapiente quod, fuga, mollitia sunt repellendus dolor quidem facere praesentium nostrum!
      Blanditiis dolores temporibus dicta mollitia atque eveniet veritatis omnis dolorem beatae ullam! Nemo earum quaerat cumque assumenda, vel nobis at veniam aut, qui ut quidem ea obcaecati, doloribus quae voluptatibus?
      Velit voluptates distinctio laboriosam, dolorem temporibus explicabo ipsum aut quaerat minus corporis sed placeat officiis optio. Atque maiores vel, amet cupiditate veritatis ea eaque? Molestiae repellendus cumque odit aut nemo.
      Maiores aperiam consequatur dolore eius voluptatum neque voluptatem tempore eum et ad reiciendis beatae pariatur soluta, dolor suscipit. Totam iste deleniti voluptate repudiandae rerum enim provident odit aliquam quasi quos!
      Vel labore tempora aperiam eum voluptatum minima odio iste? Ipsam autem laborum facilis, facere voluptas nobis maiores at laudantium corrupti cum eligendi asperiores in doloremque fugiat assumenda deleniti quas consequatur.
      Sed, incidunt. Facilis ullam, officiis adipisci incidunt fugit quas natus tempore reiciendis ab quisquam veniam animi architecto obcaecati itaque sequi numquam magni culpa aspernatur ipsa id et fugiat eum magnam.
      At natus, vero nulla tempora unde quod quibusdam. Ea minima accusamus numquam soluta maiores, fugiat architecto est deserunt corporis molestias enim esse amet culpa nobis nulla atque fugit, eaque assumenda?
      Facilis distinctio cumque quis error. Explicabo voluptatibus quo vero temporibus at numquam architecto maiores qui, fugit repudiandae deleniti amet fugiat pariatur a adipisci consequatur vitae exercitationem placeat. Praesentium, ab soluta.
      Sapiente commodi doloremque atque nulla sed eaque animi consequatur cum incidunt possimus deserunt, autem alias ullam velit inventore architecto quos aperiam dicta itaque praesentium cupiditate asperiores harum! Tempore, quaerat deserunt.
      Sunt suscipit eum voluptate laudantium numquam officiis modi doloribus nemo ducimus qui optio quas soluta reprehenderit omnis reiciendis, voluptas maxime fuga ab obcaecati, recusandae, blanditiis natus commodi praesentium possimus? Debitis!
      Quaerat earum repellendus culpa fugiat iste at excepturi odio illum hic qui, reprehenderit accusantium! Dignissimos voluptatem omnis distinctio blanditiis, dolor nisi exercitationem maiores pariatur, tenetur deleniti ducimus expedita non illo.
      Molestiae repellat repudiandae quam dicta omnis! Magnam, perspiciatis rem asperiores aliquam neque reprehenderit cum explicabo rerum deserunt iure magni molestias tempora libero ullam perferendis, consequatur nostrum debitis tempore sequi! Deleniti?
      Perferendis distinctio officia, nulla quas cumque qui, dolor delectus iusto ducimus ipsa at illum modi voluptatem facere impedit minus alias. Sit praesentium eius impedit a, voluptatem repudiandae omnis. Fuga, quo.
      Deleniti laudantium repellendus quod nesciunt dolores velit provident, tenetur soluta architecto veniam eligendi maiores. Nobis eaque voluptate suscipit placeat ducimus esse quam distinctio laborum nisi, quidem beatae praesentium? Totam, maxime.
      Natus, quidem eaque voluptates, corporis aspernatur laborum perspiciatis cupiditate itaque, illum cumque reiciendis eius eveniet quaerat! Facilis animi expedita, ducimus ipsam tenetur quibusdam repellat qui impedit ad non totam reprehenderit?
      Magni sunt iusto quibusdam pariatur? Laboriosam asperiores perferendis iste numquam voluptates voluptas optio cupiditate culpa placeat. Cupiditate, temporibus ducimus porro autem, tenetur, est perspiciatis sequi eveniet perferendis iusto quisquam molestiae.
      Iusto ratione perferendis, omnis eius odio ipsam fuga in rerum sed qui nam quod tempore quo dolorem dolores nihil praesentium quos temporibus doloremque et eum neque commodi! Amet, debitis neque?
      Pariatur dignissimos illum ullam voluptatibus beatae nulla corrupti sequi expedita laborum culpa officiis numquam facere eos sed et necessitatibus excepturi, nobis debitis suscipit ut molestiae quae id eaque! Fuga, magni.
      Enim velit facilis quibusdam corporis est architecto magnam. Unde id praesentium, recusandae cupiditate debitis voluptatibus ut sit tenetur voluptatum omnis aliquid! Eaque laudantium unde, quidem qui possimus quos officiis quam!
      Fugiat enim vero laboriosam explicabo dolorum nam blanditiis ad, voluptatem quae, quas distinctio expedita tempora quasi libero? Voluptatum et sit pariatur asperiores sapiente corporis eaque numquam. Esse praesentium fugiat debitis.
      Itaque eos perferendis et omnis velit ipsum vitae illum dolores sit in, ex architecto. Quidem sequi id, possimus debitis dolorum pariatur error recusandae nobis, quis consectetur velit similique laudantium ratione!
      Sint placeat architecto necessitatibus quae quam voluptas ad eveniet libero? Sit harum dolore pariatur porro rerum fugit voluptate, nemo laboriosam quaerat error eligendi illum vero beatae unde recusandae illo asperiores.
      Quaerat earum consequuntur impedit obcaecati illum! Suscipit dolorum aliquid veniam sed nesciunt sunt placeat illo dicta, at, dolorem nisi totam ex explicabo perspiciatis culpa rerum fuga veritatis quibusdam neque possimus!
      Voluptate placeat natus laborum tempora. Rem, voluptas rerum blanditiis dolor amet dolore incidunt fugiat! Repudiandae ad quod eveniet repellat labore optio laudantium, modi cum fugiat architecto maxime, accusantium rem dolores?
      Neque beatae voluptatibus quasi at ad amet aspernatur atque nam. Corrupti laudantium, ducimus at architecto temporibus repudiandae iusto magni nemo culpa! Fuga rerum sequi quibusdam numquam. Distinctio velit nisi adipisci.
      Aspernatur, amet voluptatibus, molestiae ab vitae iure culpa et doloremque neque quae in quidem quam eius non perspiciatis, atque sed commodi. Quidem quod suscipit illum animi beatae praesentium, veritatis delectus?
      Numquam officia mollitia, at corporis voluptatum veniam omnis impedit optio aspernatur repellat. Corporis tempore asperiores delectus vitae impedit praesentium, esse veniam atque, molestias amet fugiat laudantium. Ex minus dolorem explicabo!
      Molestiae corporis fugiat suscipit officiis rem praesentium quis ab doloribus. Esse nobis corrupti, inventore non tempore, delectus natus hic nisi recusandae, est modi doloremque saepe necessitatibus facere optio incidunt debitis.
      Voluptatibus libero tempora amet, dignissimos incidunt eius, provident labore voluptas non neque, quis tenetur repudiandae sed eum tempore fugiat ratione quo quibusdam. Magni atque eligendi laboriosam laborum ipsam incidunt reiciendis!
      Ipsum, possimus! Culpa corporis vel ex magni rem rerum nostrum nesciunt, ducimus nemo consequuntur architecto atque maiores dolores iste quisquam eum. Voluptatum libero unde suscipit nesciunt? Exercitationem aperiam aspernatur enim.
      Officiis sit sapiente repellendus, atque magnam necessitatibus saepe dolores. At id ratione unde? Architecto nam, sit dolorum soluta placeat debitis neque deserunt quasi nemo ad, reiciendis ipsam accusamus quos voluptas.
      Doloribus voluptate voluptas quasi culpa molestias, perferendis excepturi eos quibusdam officiis aut quis odit! Ratione repudiandae iusto impedit dolorum suscipit temporibus sit nihil vero adipisci doloremque, illum iure dicta eos!
      Ipsa, consequuntur! Est, sit tenetur cumque reprehenderit quo facere adipisci rerum illum ullam magni ducimus officiis vel iste eos esse dicta expedita assumenda. Tenetur omnis, voluptatum voluptatibus tempore sequi dicta.
      Facere ex dignissimos odio soluta, laudantium quisquam omnis possimus repellat laboriosam et magni assumenda magnam expedita ea? Fugiat odio inventore, veritatis, nobis velit porro laboriosam odit mollitia debitis, in at!
      Asperiores, ab. Sed perferendis cum sunt excepturi pariatur sit iure eum! Soluta exercitationem harum voluptatibus, odit tempore vitae fuga, expedita laboriosam dignissimos eos, nam consequuntur. Dolorum quidem delectus nisi minima?
      Ad velit doloribus hic quod ullam minima quas sed magnam aut rem accusamus exercitationem ex illum, perspiciatis voluptatibus ab facilis quos tempore. Nesciunt autem, minus a rerum asperiores aliquam porro.
      Vitae culpa rerum laboriosam fugiat a ad! Deleniti quam adipisci animi a enim iste aspernatur voluptate error nobis facere soluta dolorem inventore repellendus perspiciatis, molestias cumque, in voluptatum nulla. Velit?
      Eius, dolorem repellendus architecto possimus quo quidem voluptatem vitae est corporis in ducimus a minima, expedita veniam vel magni neque asperiores. Iure eveniet suscipit alias, minus molestias ab error doloremque.
      Assumenda dolore incidunt laboriosam cupiditate quidem doloremque sequi magni tempora ex laborum, officiis veritatis voluptatem aut? Harum repellendus eius saepe natus debitis asperiores excepturi facilis quam porro ad! Pariatur, sit.
      Quod, et nostrum delectus consequatur facilis quia mollitia quas tempore molestiae soluta quaerat cum est, provident iure sit. Voluptatibus quam nostrum veritatis ipsum maxime, sint neque repudiandae odio fugiat atque.
      Nesciunt voluptates excepturi ipsa illum eveniet! Iusto eligendi natus officia explicabo officiis dolore tempora voluptate consequuntur impedit, sit obcaecati laudantium eos asperiores? Iusto numquam, tempore iste modi sunt incidunt ab!
      Excepturi facere quae magnam ex dolore. Deserunt rerum et sequi, aliquam autem repellendus eum ratione natus beatae cupiditate, modi animi, voluptatem quia officiis? Soluta molestiae voluptatibus illum quibusdam architecto voluptate?
      Modi in eaque laboriosam ex at totam facilis nihil, animi dolorem rerum autem quae nulla! Labore, eligendi tenetur necessitatibus nam est recusandae, ipsa tempora assumenda ut veniam doloremque nemo enim.
      Odit veniam accusantium sunt. Natus, perspiciatis maiores soluta velit facere delectus, repudiandae quasi omnis, molestias quisquam quas porro impedit amet! Eos laboriosam aliquid id exercitationem at quae totam eligendi praesentium.
      Fugit voluptatem quos, adipisci quas obcaecati blanditiis illo molestiae facilis amet iure iusto vel ullam beatae a unde, nam sunt dolores? Voluptatum suscipit eius impedit fugit? Cumque, aut. Rem, eum!
      Exercitationem, adipisci? Natus architecto impedit unde rem. Error eveniet iure, totam tempore molestiae tempora repellat impedit qui incidunt illum eius voluptate enim accusamus. Placeat natus vitae earum odio, alias nisi!
      Eligendi, laudantium nostrum reprehenderit minus nam suscipit dolorum veritatis fuga iste aut ea hic temporibus perspiciatis nesciunt nemo voluptatibus explicabo voluptas consequatur modi nisi blanditiis totam. Pariatur assumenda nesciunt facilis?
      Minus id maiores ipsa voluptatum odio impedit nisi similique vel, et illo consequuntur ea dolor architecto soluta quisquam aperiam sapiente neque veniam! Cupiditate asperiores saepe enim placeat inventore aut mollitia!
      A quasi exercitationem voluptatum reiciendis deserunt hic et dolore, natus maxime fuga sint accusamus! Autem vero, assumenda earum reprehenderit consectetur dolorum asperiores porro excepturi iusto distinctio ut pariatur. Nulla, est!
      Nobis vero sit repudiandae provident perspiciatis dolor asperiores voluptates porro, sapiente ipsam, consectetur praesentium deleniti nemo accusamus soluta dolorum tempore totam consequuntur quas delectus quisquam! Blanditiis sequi est corporis sit!
      Sint sed nobis dolores placeat repellat sapiente maxime aut, quisquam laboriosam impedit blanditiis nihil doloremque nostrum dolor animi, nesciunt atque, eos laudantium id quas aliquid. Illum architecto ipsum id tempora.
      Saepe, consequatur accusantium, ea, quam laborum nesciunt nulla voluptatibus praesentium rerum iusto ex esse? Debitis ducimus sint tenetur explicabo, libero, architecto saepe alias similique vitae officia, magni quae ipsa dolores?
      Recusandae repudiandae saepe officiis labore odio expedita non ipsam harum, atque enim voluptates aperiam obcaecati omnis, dolores libero voluptatem illo iure animi? Placeat minus eos distinctio corrupti dignissimos aut pariatur?
      Labore repudiandae sapiente magnam architecto maxime, voluptates veritatis velit fuga sint obcaecati modi voluptatibus, in commodi id sit laboriosam assumenda odio. Quo saepe esse odit repudiandae, nulla libero officiis repellat?
      Tempore ut ipsa, libero nesciunt nisi facilis. Ea dolore nisi voluptatibus molestiae exercitationem veniam doloribus magnam quam deserunt vero eius, ipsum ullam minima doloremque repellat placeat porro totam illum voluptatem?
      Qui cum officiis et debitis maxime iste nihil quae a perspiciatis voluptatibus tempore est, illo consequuntur eos laborum aut ipsum itaque nam! Autem labore facere unde nam fugiat vitae quos!
      Facere minus odit excepturi ullam molestias totam nemo delectus rem! Necessitatibus velit ducimus incidunt praesentium quis, distinctio quam, ut, sequi odio inventore tenetur dolor voluptas id quaerat! Reprehenderit, magni dolores?
      Quis autem nobis, quasi aliquam obcaecati nesciunt! Possimus, nostrum rem. Nihil facere architecto odio, eos quis ratione saepe! Dolorum eum explicabo porro! Vitae distinctio voluptates qui illum harum a consequuntur!
      Officiis sapiente quod et illum omnis odio obcaecati ipsam dolorum ut impedit harum natus fuga, magnam ipsum praesentium quis dignissimos laborum amet aut similique laudantium officia quasi rerum quaerat. Consequuntur!
      Aliquid enim aliquam vel. Optio at sapiente natus consectetur nam, odio repudiandae. Maiores suscipit labore error minus sed commodi ea? Nostrum corrupti incidunt corporis ex accusantium voluptatem dignissimos voluptas nam.
      Ullam adipisci quis molestiae omnis culpa nisi voluptatibus praesentium, iusto earum fugit magnam voluptatum ipsam iste enim! Excepturi quisquam at soluta deserunt, blanditiis cumque minus non nisi fugiat illum debitis.
      Nam, distinctio autem culpa quaerat cumque libero omnis id tenetur quod repudiandae voluptatum perferendis praesentium rem? Voluptas, molestias sit nostrum provident amet harum unde ipsa vel perferendis, quidem omnis exercitationem.
      Explicabo quasi, illo tenetur dolores excepturi similique culpa tempore blanditiis unde nostrum dolore ipsa voluptatem aperiam itaque a at sit numquam adipisci quibusdam. Quis nostrum odit distinctio inventore sit nam!</p>
    </div>
  );
};

export default DashboardPage;
